"""initial

Revision ID: 431c29f85846
Revises: 3245e236cf8d
Create Date: 2026-01-28 17:19:36.193140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '431c29f85846'
down_revision: Union[str, Sequence[str], None] = '3245e236cf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_orders_id'), table_name='subscriber_orders')
    op.drop_index(op.f('ix_subscriber_orders_parent_tag'), table_name='subscriber_orders')
    op.drop_table('subscriber_orders')
    op.add_column('orders', sa.Column('parent_order_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('parent_tag', sa.String(length=36), nullable=True))
    op.add_column('orders', sa.Column('signal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_parent_tag'), 'orders', ['parent_tag'], unique=False)
    op.create_foreign_key(None, 'orders', 'signals', ['signal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'orders', ['parent_order_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_parent_tag'), table_name='orders')
    op.drop_column('orders', 'signal_id')
    op.drop_column('orders', 'parent_tag')
    op.drop_column('orders', 'parent_order_id')
    op.create_table('subscriber_orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_order_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_tag', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('subscriber_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('broker_order_id', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('meta_data', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], name=op.f('subscriber_orders_ibfk_1'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['demat_apis.id'], name=op.f('subscriber_orders_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_subscriber_orders_parent_tag'), 'subscriber_orders', ['parent_tag'], unique=False)
    op.create_index(op.f('ix_subscriber_orders_id'), 'subscriber_orders', ['id'], unique=False)
    # ### end Alembic commands ###
