"""subscriber order model

Revision ID: 43c8fe81365b
Revises: 17a99449a4bc
Create Date: 2026-01-26 14:08:20.961080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43c8fe81365b'
down_revision: Union[str, Sequence[str], None] = '17a99449a4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_order_id', sa.Integer(), nullable=True),
    sa.Column('parent_tag', sa.String(length=36), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['demat_apis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_orders_id'), 'subscriber_orders', ['id'], unique=False)
    op.create_index(op.f('ix_subscriber_orders_parent_tag'), 'subscriber_orders', ['parent_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriber_orders_parent_tag'), table_name='subscriber_orders')
    op.drop_index(op.f('ix_subscriber_orders_id'), table_name='subscriber_orders')
    op.drop_table('subscriber_orders')
    # ### end Alembic commands ###
