"""minor tweeks

Revision ID: 63ce5d994671
Revises: 73227d07427c
Create Date: 2026-02-04 10:44:52.299204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63ce5d994671'
down_revision: Union[str, Sequence[str], None] = '73227d07427c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instruments', 'lot_size',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_parent_tag'), table_name='orders')
    op.drop_constraint(op.f('orders_ibfk_2'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'parent_order_id')
    op.drop_column('orders', 'parent_tag')
    op.add_column('signals', sa.Column('type', sa.Enum('ENTER_POSITION', 'EXIT_POSITION', name='signaltype'), nullable=False))
    op.add_column('signals', sa.Column('depends_on_signal_id', sa.Integer(), nullable=True))
    op.add_column('strategy_subscriptions', sa.Column('total_fund', sa.Float(), nullable=False))
    op.add_column('strategy_subscriptions', sa.Column('fund_allocation_precentage', sa.Float(), nullable=False))
    op.drop_column('strategy_subscriptions', 'multiplier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategy_subscriptions', sa.Column('multiplier', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('strategy_subscriptions', 'fund_allocation_precentage')
    op.drop_column('strategy_subscriptions', 'total_fund')
    op.drop_column('signals', 'depends_on_signal_id')
    op.drop_column('signals', 'type')
    op.add_column('orders', sa.Column('parent_tag', mysql.VARCHAR(length=36), nullable=True))
    op.add_column('orders', sa.Column('parent_order_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('orders_ibfk_2'), 'orders', 'orders', ['parent_order_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_orders_parent_tag'), 'orders', ['parent_tag'], unique=False)
    op.alter_column('instruments', 'lot_size',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
