"""Instrument update

Revision ID: fc5801132769
Revises: 43c8fe81365b
Create Date: 2026-01-28 10:39:01.819911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fc5801132769'
down_revision: Union[str, Sequence[str], None] = '43c8fe81365b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(length=12), nullable=False),
    sa.Column('exchange', sa.Enum('NSECM', 'NSEFO', 'BSECM', 'BSEFO', name='exchange'), nullable=False),
    sa.Column('trading_symbol', sa.String(length=100), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=False),
    sa.Column('instrument_type', sa.Enum('EQ', 'FUT', 'OPT', name='instrumenttype'), nullable=False),
    sa.Column('lot_size', sa.String(length=10), nullable=False),
    sa.Column('freeze_quantity', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(length=10), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('option_type', sa.Enum('CE', 'PE', name='optiontype'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.add_column('orders', sa.Column('instrument_id', sa.String(length=12), nullable=False))
    op.drop_column('orders', 'instrument_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('instrument_token', mysql.VARCHAR(length=12), nullable=False))
    op.drop_column('orders', 'instrument_id')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    # ### end Alembic commands ###
